# .github/workflows/deploy.yml
name: Deploy Pratish Portfolio to GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - 'public/**'
      - '**.ts'
      - '**.tsx'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint check
        run: pnpm run lint

      - name: lint fix
        run: pnpm run lint:fix

      - name: formatting through prettier
        run: pnpm run format

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build & Export
        run: pnpm run build

      - name: Verify exported files
        run: |
          echo "Listing contents of 'out/' directory:"
          ls -R out/
          echo "Checking for 'pratish.json'..."
          if [ -f out/pratish.json ]; then echo "✔ pratish.json found"; else echo "✖ pratish.json missing"; exit 1; fi
          echo "Checking for 'Pratish.webp'..."
          if [ -f out/Pratish.webp ]; then echo "✔ Pratish.webp found"; else echo "✖ Pratish.webp missing"; exit 1; fi

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
